name: anpi_report_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.5+17

environment:
  sdk: '>=3.6.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  file_picker:
  path_provider:
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.12.1 #^2.25.4
  cloud_firestore: ^5.6.5
  firebase_storage:
  firebase_auth:
  firebase_messaging:
  image_picker:
  provider:
  rxdart:
  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:
  flutter_riverpod:
  freezed_annotation:
  json_annotation:
  flutter_slidable:
  ionicons:
  googleapis_auth:
  http:
  logger:
  intl:
  font_awesome_flutter:
  uuid:
  excel:
  dropdown_button2:
  firebase_admin:
  flutter_dotenv:
  timeago:
  flutter_datetime_picker_plus:
  flutter_custom_selector:
  flutter_form_builder:
  form_builder_validators:
  flutter_settings_screens:
  flutter_local_notifications:
  nil:
  data_table_2:
  geolocator:
  geocoding:
  custom_text_form_field_plus:
  device_info_plus:
  ios_utsname_ext:
  device_imei:
  flutter_device_identifier:
  flutter_app_badger:
  badges:
  flutter_launcher_icons:
  url_launcher:
  app_settings:
  permission_handler:
  flutter_secure_storage: ^9.2.4
  auto_route: ^10.0.0 # ^9.3.0+1 # ^8.3.0
  quickalert:
  webview_flutter:
  firestore_cache:
  sqflite:
  path:
  mobile_scanner:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  riverpod_generator:
  freezed:
  json_serializable:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0 #^3.0.0
  auto_route_generator: ^10.0.1

#dependency_overrides:
#  meta: ">=1.12.0 <1.16.0"

  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "lib/assets/icon_iOS.png"
  image_path_android: "lib/assets/icon_Android.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "lib/assets/icon_Android.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
