// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIGcFbtC8zZ2PaFX9gneKo07mh2IoT_DM',
    appId: '1:482610373416:android:669c9c4d45212750d5661d',
    messagingSenderId: '482610373416',
    projectId: 'anpi-report-2024',
    storageBucket: 'anpi-report-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG309C2cvmAgQr2Fq0ChRMLy1-tG_rieY',
    appId: '1:482610373416:ios:ca49d589bd308f1dd5661d',
    messagingSenderId: '482610373416',
    projectId: 'anpi-report-2024',
    storageBucket: 'anpi-report-2024.appspot.com',
    iosBundleId: 'com.katoanpireport.flutter.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiAWPBG-oqqior8mfLmkaODAr1B_5516Q',
    appId: '1:482610373416:web:dc6d2175f3c91feed5661d',
    messagingSenderId: '482610373416',
    projectId: 'anpi-report-2024',
    authDomain: 'anpi-report-2024.firebaseapp.com',
    storageBucket: 'anpi-report-2024.appspot.com',
    measurementId: 'G-GTMQWF75PR',
  );

}